const Arweave = require("arweave");

const arweave = Arweave.init({});

/**
 * @returns {JWKInterface} wallet object generated by Arweave.
 */
module.exports = function WalletFuzzer() {
    return async() => { 
        return await arweave.wallets.generate();
    };
}
