import Arweave from "arweave";

const arweave = Arweave.init({});

/**
 * @returns {JWKInterface} wallet object generated by Arweave.
 */
export default function WalletFuzzer() {
    return async() => { 
        return await arweave.wallets.generate();
    };
}
